### ISSUE TITLE
Doesn't build on OSX

### ISSUE THREAD

**Issue by alxndrsn** [w8rbt/oathgen#1]
Calling `build.sh` in Bash 3.2 gives the following errors:

> $ ./build.sh
./build.sh: line 15: [: too many arguments
./build.sh: line 23: [: too many arguments
./build.sh: line 30: [: too many arguments
./build.sh: line 38: [: too many arguments
./build.sh: line 46: [: too many arguments
./build.sh: line 50: [: too many arguments

**Comment by w8rbt** [comment]
alxndrsn, `build.sh` takes an argument. So you should use it like this, `build.sh mac`. There is an empty slot in the script for OSX:

if [ $1 == 'Mac' -o $1 == 'mac' ]
    then echo nothing yet
fi

I don't have a Mac, so I have not built oathgen for OSX, however, it should be easy to do. Look at the other targets in the script and how they are built, and do something similar on OSX.

**Comment by alxndrsn** [comment]
Thanks, I'll take a look at getting it working.
