### ISSUE TITLE
Missing a license file

### ISSUE THREAD

**Issue by lllama** [w8rbt/oathgen#3]
Would it be possible to know what license this code is released under?

**Comment by w8rbt** [comment]
Each source code file in oathgen contains the copyright and the license (look at the very top of each file). Oathgen uses the ISC license. It is a BSD license.

**Comment by lllama** [comment]
Apologies - I'd had a quick search for "license" and "BSD" but didn't, y'know, actually look at the code. :)

**Comment by w8rbt** [comment]
No trouble. I hope you find it useful.
