### ISSUE TITLE
Feature request: accept secret via stdin

### ISSUE THREAD

**Issue by avih** [w8rbt/oathgen#5]
As far as I can tell, oathgen doesn't support accepting the secret via stdin (do correct me if I'm wrong).

This could be useful If one wants to keep the secret encrypted and then pipe the plaintext secret it to oathgen.

Possible syntax e.g. `mydecrypt path/to/encrypted-secret | oathgen -s -`, where `mydecrypt` could for instance prompt for passphrase, or maybe uses some keyring etc.

If there could be a case where the secret would be the string `-`, then maybe another syntax would be required.

**Comment by w8rbt** [comment]
You are correct, oathgen only accepts the secret in a text file or as a command line argument. I just added the ability to pass the secret via stdin. Use it like this: 

    decrypt secret_file | oathgen -s stdin

Let me know how it works.

**Comment by avih** [comment]
Thanks for the quick response. I confirm it seems to be working well (and the patch seems simple enough to not suspect it won't work on some cases).

It took me a while to build it since it's the first time I tried, and I'm cross compiling on linux for windows (using MXE), and I had to build `cryptopp` as well, and then again with `alt_base32`.

But eventually I got an `oathgen.exe` which runs on windows and produces the same output as your prebuilt binary when using secret in a file or as direct argument, and also the same output when the secret is piped and `-s stdin` is used.

Thanks again.

**Comment by avih** [comment]
Hmm.. I'm not sure the built in help was modified correctly though. You updated the help for `-f`, but as far as I can tell the functionality has changed for `-s` only.

**Comment by w8rbt** [comment]
Thanks avih. That was a mistake. I corrected the help information.

**Comment by avih** [comment]
Thanks for creating and maintaining oathgen :)
